version: "3"

services:

  census:
    build:
      context: .
      dockerfile: ./Dockerfiles/census.Dockerfile
    image: census:latest
    expose:
      - 80
    ports:
      - 3001:80

  census-api-build:
    build:
      context: .
      dockerfile: ./Dockerfiles/census-api-build.Dockerfile
    image: census-api-build:latest

  census-api-test:
    build:
      context: .
      dockerfile: ./Dockerfiles/census-api-test.Dockerfile
    image: census-api-test:latest
    depends_on:
      - census-api-build

  census-api:
    build:
      context: .
      dockerfile: ./Dockerfiles/census-api.Dockerfile
    image: census-api:latest
    depends_on:
      - census-api-build
    expose:
      - 80
    ports:
      - 3002:80

